// lib/env.js
export const OPENAI_API_KEY = process.env.OPENAI_API_KEY;

export const CRON_SECRET = process.env.CRON_SECRET;
export const UPSTASH_REST_TOKEN = process.env.UPSTASH_REST_TOKEN;
export const UPSTASH_REST_URL = process.env.UPSTASH_REST_URL;

export const AFFILIATOR_MIN_SCORE_AUTO = process.env.AFFILIATOR_MIN_SCORE_AUTO;
export const AFFILIATOR_MIN_SCORE_DEALS = process.env.AFFILIATOR_MIN_SCORE_DEALS;
export const AFFILIATOR_SOURCES = process.env.AFFILIATOR_SOURCES;
export const AFFILIATOR_MODE = process.env.AFFILIATOR_MODE;

export const AFFILIATOR_MIN_SCORE_HALAL = process.env.AFFILIATOR_MIN_SCORE_HALAL;
export const AFFILIATOR_MIN_SCORE_CRYPTO = process.env.AFFILIATOR_MIN_SCORE_CRYPTO;
export const AFFILIATOR_MIN_SCORE_IMMO = process.env.AFFILIATOR_MIN_SCORE_IMMO;

export const AFFILIATOR_BASE_URL = process.env.AFFILIATOR_BASE_URL;
export const ALIEXPRESS_AFFILIATE_LINK = process.env.ALIEXPRESS_AFFILIATE_LINK;
export const AMAZON_ASSOCIATE_TAG = process.env.AMAZON_ASSOCIATE_TAG;

export const TELEGRAM_CHAT_ID_AUTO = process.env.TELEGRAM_CHAT_ID_AUTO;
export const TELEGRAM_CHAT_ID_DEALS = process.env.TELEGRAM_CHAT_ID_DEALS;
export const TELEGRAM_BOT_TOKEN_AUTO = process.env.TELEGRAM_BOT_TOKEN_AUTO;
export const TELEGRAM_BOT_TOKEN_DEALS = process.env.TELEGRAM_BOT_TOKEN_DEALS;
